// POST /api/onboard: FAST account creation (a few seconds, no AI in the hot
// path). The member instantly gets a procedural scout panda and their Agentic
// ID mint; the photoreal portrait is generated by /api/portrait right after
// (retryable, never blocks the flow). Ordering is heal-friendly: the agent row
// exists before the mint, so a retry never double-mints.
import { NextResponse } from "next/server";
import { keccak256, toBytes, parseEventLogs } from "viem";
import { verifyAuth } from "@/lib/privy";
import { db } from "@/lib/db";
import { proceduralPanda, pandaPrompt } from "@/lib/panda";
import { AGENT_CONTRACT, relayerWrite, publicClient, explorerTx } from "@/lib/chain";
import { agentAbi } from "@/lib/abi";

export const maxDuration = 60;

export async function POST(req: Request) {
  try {
    const auth = await verifyAuth(req);
    const body = await req.json();
    const { country, worlds, worldOther, socials, vibe, palette } = body;
    if (!country) {
      return NextResponse.json({ error: "country required" }, { status: 400 });
    }
    const worldList: string[] = Array.isArray(worlds) ? worlds : [];

    const client = db();

    // Upsert user (intro consent is per-event, captured at claim time)
    const { data: user, error: userErr } = await client
      .from("users")
      .upsert(
        {
          email: auth.email,
          privy_id: auth.privyId,
          wallet: auth.wallet,
          country,
          socials: socials || {},
        },
        { onConflict: "email" }
      )
      .select()
      .single();
    if (userErr) throw userErr;

    const traits = {
      country,
      worlds: worldList,
      worldOther: worldOther || undefined,
      vibe: vibe || "curious",
      palette: palette || "purple",
    };

    // Idempotency: existing agent -> return it (portrait/mint heal via /api/portrait)
    const { data: existing } = await client.from("agents").select("*").eq("user_id", user.id).maybeSingle();
    if (existing) {
      return NextResponse.json({
        user,
        agent: existing,
        existed: true,
        mint: existing.mint_tx
          ? { tx: existing.mint_tx, explorer: explorerTx(existing.mint_tx), tokenId: existing.token_id?.toString() ?? null }
          : null,
      });
    }

    // Instant scout panda (procedural, cannot fail): the account is usable
    // immediately even if everything downstream hiccups.
    const svg = proceduralPanda(traits);
    const { data: agent, error: agentErr } = await client
      .from("agents")
      .insert({
        user_id: user.id,
        panda_image_url: `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`,
        panda_prompt: pandaPrompt(traits),
        panda_fallback: true,
        traits,
      })
      .select()
      .single();
    if (agentErr) throw agentErr;

    // Mint the Agentic ID (profile committed as hashes, never plaintext).
    // Agent row exists first, so a retry after a mid-mint failure won't remint.
    const profileJson = JSON.stringify({ country, worlds: worldList, worldOther, socials: socials || {} });
    let tokenId: bigint | null = null;
    let mintTx: string | null = null;
    if (AGENT_CONTRACT && auth.wallet && process.env.RELAYER_KEYS) {
      try {
        const datas = [
          { dataDescription: "profile_v1", dataHash: keccak256(toBytes(profileJson)) },
          { dataDescription: "memory_root", dataHash: keccak256(toBytes(`genesis:${user.id}`)) },
        ];
        const { hash } = await relayerWrite({
          address: AGENT_CONTRACT,
          abi: agentAbi,
          functionName: "iMintWithRole",
          args: [auth.wallet, datas, auth.wallet],
        });
        mintTx = hash;
        const receipt = await publicClient.getTransactionReceipt({ hash });
        const transfers = parseEventLogs({ abi: agentAbi, logs: receipt.logs, eventName: "Transfer" });
        tokenId = transfers[0]?.args?.tokenId ?? null;
        await client
          .from("agents")
          .update({ token_id: tokenId !== null ? Number(tokenId) : null, mint_tx: mintTx })
          .eq("user_id", user.id);
      } catch (e) {
        // Mint heals later via /api/portrait; never block the human at the door.
        console.error("[onboard] mint deferred:", e instanceof Error ? e.message : e);
      }
    }

    // Memory mirror ("what my panda knows" reads from here)
    const worldText = [...worldList, worldOther].filter(Boolean).join(", ") || "unspecified";
    await client.from("memories").insert({
      user_id: user.id,
      kind: "profile",
      summary: `Joined from ${country}. World: ${worldText}.`,
    });

    return NextResponse.json({
      user,
      agent: { ...agent, token_id: tokenId !== null ? Number(tokenId) : null, mint_tx: mintTx },
      mint: mintTx ? { tx: mintTx, explorer: explorerTx(mintTx), tokenId: tokenId?.toString() ?? null } : null,
    });
  } catch (e) {
    console.error("[onboard]", e);
    return NextResponse.json({ error: e instanceof Error ? e.message : "onboard failed" }, { status: 500 });
  }
}
